In [1]:
import pandas as pd
# pandas é uma biblioteca de código aberto para análise de dados em Python. Ela fornece estruturas de dados e funções para manipulação e análise de dados de forma eficiente. A função pd.Series() é usada para criar uma série, que é uma estrutura de dados unidimensional semelhante a um array, mas com rótulos (índices) associados a cada elemento. No exemplo fornecido, pd.Series([10,8,7,9]) cria uma série com os valores 10, 8, 7 e 9.

In [2]:
pd.Series([10,8,7,9])

# O código acima cria uma série do pandas com os valores 10, 8, 7 e 9. A série é uma estrutura de dados unidimensional que pode conter qualquer tipo de dados, como números, strings ou objetos. Cada elemento da série é associado a um índice, que por padrão é um número inteiro começando em 0. Portanto, a série criada terá os seguintes índices e valores:
# Índice: 0, Valor: 10
# Índice: 1, Valor: 8
# Índice: 2, Valor: 7
# Índice: 3, Valor: 9

0    10
1     8
2     7
3     9
dtype: int64

In [7]:
notas = pd.Series([10,8,7,9])
notas.mean() # O método mean() calcula a média dos valores na série.
notas.sum() # O método sum() calcula a soma dos valores na série.
notas.max() # O método max() retorna o valor máximo na série.
notas.min() # O método min() retorna o valor mínimo na série.
notas.describe() # O método describe() fornece uma descrição estatística dos dados na série, incluindo contagem, média, desvio padrão, valores mínimo e máximo, e os quartis.
notas.value_counts() # O método value_counts() conta a frequência de cada valor único na série e retorna uma série com os valores únicos como índices e suas respectivas contagens como valores.
notas.sort_values() # O método sort_values() ordena os valores na série em ordem crescente. Se você quiser ordenar em ordem decrescente, pode usar notas.sort_values(ascending=False).
notas.sort_index() # O método sort_index() ordena os valores na série com base nos índices. Se os índices forem numéricos, eles serão ordenados em ordem crescente. Se os índices forem strings, eles serão ordenados em ordem alfabética.
notas[0] # Acessa o valor na posição de índice 0, que é 10.
notas.std() # O método std() calcula o desvio padrão dos valores na série, que é uma medida de dispersão que indica o quanto os valores estão espalhados em relação à média.
notas.median() # O método median() calcula a mediana dos valores na série,

np.float64(8.5)

In [ ]:
df = pd.DataFrame({
    "Alunos": ["Alfredo", "Abel", "Henrique", "Julia", "Carlos"],
    "Faltas": [1, 8, 4, 0, 2],
    "Prova": [10, 9.8, 4.5, 8.5, 7.8]
})
# Dataframe é uma estrutura de dados bidimensional, semelhante a uma tabela, que pode conter diferentes tipos de dados em suas colunas. Ele é amplamente utilizado para manipulação e análise de dados em Python. O código acima cria um DataFrame com três colunas: "Alunos", "Faltas" e "Prova". Cada coluna contém uma lista de valores correspondentes aos alunos, suas faltas e suas notas na prova.
df

     Alunos  Faltas  Prova
0   Alfredo       1   10.0
1      Abel       8    9.8
2  Henrique       4    4.5
3     Julia       0    8.5
4    Carlos       2    7.8

In [ ]:
df.iloc[0] # O método iloc é usado para acessar linhas ou colunas específicas em um DataFrame com base em sua posição. No exemplo acima, df.iloc[0] retorna a primeira linha do DataFrame, que contém as informações do aluno "Alfredo", suas faltas e sua nota na prova.

Alunos    Alfredo
Faltas          1
Prova        10.0
Name: 0, dtype: object

In [ ]:
df.columns # O atributo columns retorna os rótulos das colunas do DataFrame. No exemplo acima, df.columns retornará um objeto Index contendo os rótulos "Alunos", "Faltas" e "Prova". Esses rótulos podem ser usados para acessar ou manipular as colunas do DataFrame.

Index(['Alunos', 'Faltas', 'Prova'], dtype='object')

In [12]:
df.dtypes # O atributo dtypes retorna os tipos de dados de cada coluna no DataFrame. No exemplo acima, df.dtypes retornará um objeto Series indicando que a coluna "Alunos" é do tipo object (string), a coluna "Faltas" é do tipo int64 (inteiro) e a coluna "Prova" é do tipo float64 (número decimal).

Alunos     object
Faltas      int64
Prova     float64
dtype: object

In [16]:
df["Prova"] > 8 # O código df["Prova"] > 8 cria uma série booleana que indica quais alunos tiveram uma nota na prova maior que 8. No exemplo acima, isso retornará uma série com os seguintes valores:

0     True
1     True
2    False
3     True
4    False
Name: Prova, dtype: bool

In [17]:
df[df["Prova"] > 8] # O código df[df["Prova"] > 8] retorna um DataFrame filtrado que contém apenas as linhas onde a condição df["Prova"] > 8 é verdadeira. Isso significa que o DataFrame resultante incluirá apenas os alunos que tiveram uma nota na prova maior que 8. No exemplo acima, isso retornará um DataFrame com as informações dos alunos "Alfredo" e "Abel", que tiveram notas de 10 e 9.8, respectivamente.

    Alunos  Faltas  Prova
0  Alfredo       1   10.0
1     Abel       8    9.8
3    Julia       0    8.5

In [ ]:
pd.read_csv("dados.csv", sep=",") # O código pd.read_csv("dados.csv", sep=",") é usado para ler um arquivo CSV (Comma-Separated Values) e criar um DataFrame a partir dos dados contidos nesse arquivo. O argumento "dados.csv" é o nome do arquivo que você deseja ler. Certifique-se de que o arquivo esteja no mesmo diretório do seu script ou forneça o caminho completo para o arquivo. Após a execução desse código, você terá um DataFrame contendo os dados do arquivo CSV, que pode ser manipulado e analisado usando as funcionalidades do pandas.

# outros métodos de leitura de arquivos incluem:
pd.read_excel("dados.xlsx") # para ler arquivos do Excel
pd.read_json("dados.json") # para ler arquivos JSON
pd.read_sql("SELECT * FROM tabela", con=conexao) # para ler dados de um banco de dados SQL, onde "tabela" é o nome da tabela que você deseja ler e "conexao" é a conexão estabelecida com o banco de dados.

In [18]:
df.head() # O método head() exibe as primeiras linhas do DataFrame. Por padrão, ele mostra as 5 primeiras linhas, mas você pode especificar um número diferente como argumento, por exemplo, df.head(3) para mostrar as 3 primeiras linhas.

     Alunos  Faltas  Prova
0   Alfredo       1   10.0
1      Abel       8    9.8
2  Henrique       4    4.5
3     Julia       0    8.5
4    Carlos       2    7.8

In [ ]:
df.head(3) # O código df.head(3) exibe as 3 primeiras linhas do DataFrame. Isso é útil para obter uma visão rápida dos dados e verificar se eles foram carregados corretamente.

     Alunos  Faltas  Prova
0   Alfredo       1   10.0
1      Abel       8    9.8
2  Henrique       4    4.5